# fly.toml app configuration file generated for invitationisa on 2026-09-21T22:34:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'invitationisa'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  ADDR = ':8080'
  COOKIE_SAMESITE = 'none'
  DATABASE_DSN = 'file:/data/invitation.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(5000)&_pragma=foreign_keys(1)'
  STORAGE_DRIVER = 'local'
  STORAGE_LOCAL_DIR = '/data/media'

[[mounts]]
  source = 'datos'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
